// Code generated by protoc-gen-go.
// source: steakhouse.proto
// DO NOT EDIT!

/*
Package steakhouse is a generated protocol buffer package.

It is generated from these files:
	steakhouse.proto

It has these top-level messages:
	Cuisine
	Menu
	Intstr
	Order
	Query
	Status
*/
package steakhouse

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Cuisine struct {
	Title       string            `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Description string            `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Price       float32           `protobuf:"fixed32,3,opt,name=price" json:"price,omitempty"`
	Id          string            `protobuf:"bytes,4,opt,name=id" json:"id,omitempty"`
	IsDeleted   bool              `protobuf:"varint,5,opt,name=is_deleted,json=isDeleted" json:"is_deleted,omitempty"`
	Metadata    map[string]string `protobuf:"bytes,6,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Cuisine) Reset()                    { *m = Cuisine{} }
func (m *Cuisine) String() string            { return proto.CompactTextString(m) }
func (*Cuisine) ProtoMessage()               {}
func (*Cuisine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Cuisine) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Menu struct {
	Title       string     `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Description string     `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Cuisines    []*Cuisine `protobuf:"bytes,3,rep,name=cuisines" json:"cuisines,omitempty"`
	Id          string     `protobuf:"bytes,4,opt,name=id" json:"id,omitempty"`
}

func (m *Menu) Reset()                    { *m = Menu{} }
func (m *Menu) String() string            { return proto.CompactTextString(m) }
func (*Menu) ProtoMessage()               {}
func (*Menu) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Menu) GetCuisines() []*Cuisine {
	if m != nil {
		return m.Cuisines
	}
	return nil
}

type Intstr struct {
	Num  int32  `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Intstr) Reset()                    { *m = Intstr{} }
func (m *Intstr) String() string            { return proto.CompactTextString(m) }
func (*Intstr) ProtoMessage()               {}
func (*Intstr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Order struct {
	CreatedAt int64   `protobuf:"varint,1,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt int64   `protobuf:"varint,2,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	Discount  *Intstr `protobuf:"bytes,3,opt,name=discount" json:"discount,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Order) GetDiscount() *Intstr {
	if m != nil {
		return m.Discount
	}
	return nil
}

type Query struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Status struct {
	Code int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*Cuisine)(nil), "steakhouse.Cuisine")
	proto.RegisterType((*Menu)(nil), "steakhouse.menu")
	proto.RegisterType((*Intstr)(nil), "steakhouse.intstr")
	proto.RegisterType((*Order)(nil), "steakhouse.order")
	proto.RegisterType((*Query)(nil), "steakhouse.Query")
	proto.RegisterType((*Status)(nil), "steakhouse.status")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Steakhouse service

type SteakhouseClient interface {
	GetCuisine(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Cuisine, error)
	GetCuisines(ctx context.Context, in *Query, opts ...grpc.CallOption) (Steakhouse_GetCuisinesClient, error)
	UpdateCuisine(ctx context.Context, in *Cuisine, opts ...grpc.CallOption) (*Status, error)
	DeleteCuisine(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Status, error)
	CreateCuisine(ctx context.Context, opts ...grpc.CallOption) (Steakhouse_CreateCuisineClient, error)
}

type steakhouseClient struct {
	cc *grpc.ClientConn
}

func NewSteakhouseClient(cc *grpc.ClientConn) SteakhouseClient {
	return &steakhouseClient{cc}
}

func (c *steakhouseClient) GetCuisine(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Cuisine, error) {
	out := new(Cuisine)
	err := grpc.Invoke(ctx, "/steakhouse.Steakhouse/GetCuisine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *steakhouseClient) GetCuisines(ctx context.Context, in *Query, opts ...grpc.CallOption) (Steakhouse_GetCuisinesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Steakhouse_serviceDesc.Streams[0], c.cc, "/steakhouse.Steakhouse/GetCuisines", opts...)
	if err != nil {
		return nil, err
	}
	x := &steakhouseGetCuisinesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Steakhouse_GetCuisinesClient interface {
	Recv() (*Cuisine, error)
	grpc.ClientStream
}

type steakhouseGetCuisinesClient struct {
	grpc.ClientStream
}

func (x *steakhouseGetCuisinesClient) Recv() (*Cuisine, error) {
	m := new(Cuisine)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *steakhouseClient) UpdateCuisine(ctx context.Context, in *Cuisine, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/steakhouse.Steakhouse/UpdateCuisine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *steakhouseClient) DeleteCuisine(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/steakhouse.Steakhouse/DeleteCuisine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *steakhouseClient) CreateCuisine(ctx context.Context, opts ...grpc.CallOption) (Steakhouse_CreateCuisineClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Steakhouse_serviceDesc.Streams[1], c.cc, "/steakhouse.Steakhouse/CreateCuisine", opts...)
	if err != nil {
		return nil, err
	}
	x := &steakhouseCreateCuisineClient{stream}
	return x, nil
}

type Steakhouse_CreateCuisineClient interface {
	Send(*Cuisine) error
	Recv() (*Status, error)
	grpc.ClientStream
}

type steakhouseCreateCuisineClient struct {
	grpc.ClientStream
}

func (x *steakhouseCreateCuisineClient) Send(m *Cuisine) error {
	return x.ClientStream.SendMsg(m)
}

func (x *steakhouseCreateCuisineClient) Recv() (*Status, error) {
	m := new(Status)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Steakhouse service

type SteakhouseServer interface {
	GetCuisine(context.Context, *Query) (*Cuisine, error)
	GetCuisines(*Query, Steakhouse_GetCuisinesServer) error
	UpdateCuisine(context.Context, *Cuisine) (*Status, error)
	DeleteCuisine(context.Context, *Query) (*Status, error)
	CreateCuisine(Steakhouse_CreateCuisineServer) error
}

func RegisterSteakhouseServer(s *grpc.Server, srv SteakhouseServer) {
	s.RegisterService(&_Steakhouse_serviceDesc, srv)
}

func _Steakhouse_GetCuisine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SteakhouseServer).GetCuisine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steakhouse.Steakhouse/GetCuisine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SteakhouseServer).GetCuisine(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _Steakhouse_GetCuisines_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Query)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SteakhouseServer).GetCuisines(m, &steakhouseGetCuisinesServer{stream})
}

type Steakhouse_GetCuisinesServer interface {
	Send(*Cuisine) error
	grpc.ServerStream
}

type steakhouseGetCuisinesServer struct {
	grpc.ServerStream
}

func (x *steakhouseGetCuisinesServer) Send(m *Cuisine) error {
	return x.ServerStream.SendMsg(m)
}

func _Steakhouse_UpdateCuisine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cuisine)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SteakhouseServer).UpdateCuisine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steakhouse.Steakhouse/UpdateCuisine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SteakhouseServer).UpdateCuisine(ctx, req.(*Cuisine))
	}
	return interceptor(ctx, in, info, handler)
}

func _Steakhouse_DeleteCuisine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SteakhouseServer).DeleteCuisine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steakhouse.Steakhouse/DeleteCuisine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SteakhouseServer).DeleteCuisine(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _Steakhouse_CreateCuisine_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SteakhouseServer).CreateCuisine(&steakhouseCreateCuisineServer{stream})
}

type Steakhouse_CreateCuisineServer interface {
	Send(*Status) error
	Recv() (*Cuisine, error)
	grpc.ServerStream
}

type steakhouseCreateCuisineServer struct {
	grpc.ServerStream
}

func (x *steakhouseCreateCuisineServer) Send(m *Status) error {
	return x.ServerStream.SendMsg(m)
}

func (x *steakhouseCreateCuisineServer) Recv() (*Cuisine, error) {
	m := new(Cuisine)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Steakhouse_serviceDesc = grpc.ServiceDesc{
	ServiceName: "steakhouse.Steakhouse",
	HandlerType: (*SteakhouseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCuisine",
			Handler:    _Steakhouse_GetCuisine_Handler,
		},
		{
			MethodName: "UpdateCuisine",
			Handler:    _Steakhouse_UpdateCuisine_Handler,
		},
		{
			MethodName: "DeleteCuisine",
			Handler:    _Steakhouse_DeleteCuisine_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCuisines",
			Handler:       _Steakhouse_GetCuisines_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CreateCuisine",
			Handler:       _Steakhouse_CreateCuisine_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("steakhouse.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x94, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0xc7, 0x99, 0xdd, 0x24, 0x26, 0x27, 0xa6, 0xc4, 0xb1, 0xea, 0x12, 0x15, 0xe2, 0x5e, 0x85,
	0x5c, 0x64, 0x6b, 0xbc, 0x91, 0x88, 0x17, 0xa5, 0x8a, 0x57, 0x15, 0x5d, 0xed, 0x75, 0x19, 0x77,
	0x0e, 0x71, 0x68, 0xb2, 0x1b, 0x76, 0xce, 0x16, 0x82, 0x88, 0xd0, 0x57, 0xf0, 0x2d, 0x7c, 0x1d,
	0x5f, 0xc1, 0x07, 0x91, 0xf9, 0x48, 0xba, 0xb5, 0x41, 0xb4, 0x77, 0x67, 0xce, 0xd7, 0xfe, 0xfe,
	0xff, 0x19, 0x16, 0xfa, 0x9a, 0x50, 0x9c, 0x7d, 0x2e, 0x2a, 0x8d, 0x93, 0x55, 0x59, 0x50, 0xc1,
	0xe1, 0x32, 0x33, 0x78, 0x34, 0x2f, 0x8a, 0xf9, 0x02, 0x13, 0xb1, 0x52, 0x89, 0xc8, 0xf3, 0x82,
	0x04, 0xa9, 0x22, 0xd7, 0xae, 0x33, 0xbe, 0x08, 0xe0, 0xd6, 0x51, 0xa5, 0xb4, 0xca, 0x91, 0xef,
	0x43, 0x93, 0x14, 0x2d, 0x30, 0x62, 0x43, 0x36, 0xea, 0xa4, 0xee, 0xc0, 0x87, 0xd0, 0x95, 0xa8,
	0xb3, 0x52, 0xad, 0xcc, 0x5c, 0x14, 0xd8, 0x5a, 0x3d, 0x65, 0xe6, 0x56, 0xa5, 0xca, 0x30, 0x0a,
	0x87, 0x6c, 0x14, 0xa4, 0xee, 0xc0, 0xf7, 0x20, 0x50, 0x32, 0x6a, 0xd8, 0xf6, 0x40, 0x49, 0xfe,
	0x18, 0x40, 0xe9, 0x53, 0x89, 0x0b, 0x24, 0x94, 0x51, 0x73, 0xc8, 0x46, 0xed, 0xb4, 0xa3, 0xf4,
	0x2b, 0x97, 0xe0, 0x2f, 0xa1, 0xbd, 0x44, 0x12, 0x52, 0x90, 0x88, 0x5a, 0xc3, 0x70, 0xd4, 0x9d,
	0x3e, 0x99, 0xd4, 0x74, 0x79, 0xc6, 0xc9, 0xb1, 0xef, 0x79, 0x9d, 0x53, 0xb9, 0x4e, 0xb7, 0x23,
	0x83, 0x17, 0xd0, 0xbb, 0x52, 0xe2, 0x7d, 0x08, 0xcf, 0x70, 0xed, 0xa5, 0x98, 0xd0, 0x60, 0x9e,
	0x8b, 0x45, 0x85, 0x5e, 0x82, 0x3b, 0xcc, 0x82, 0xe7, 0x2c, 0xfe, 0x06, 0x8d, 0x25, 0xe6, 0xd5,
	0x8d, 0x0d, 0x48, 0xa0, 0x9d, 0x39, 0x3e, 0x1d, 0x85, 0x96, 0xfd, 0xee, 0x0e, 0xf6, 0x74, 0xdb,
	0xf4, 0xa7, 0x37, 0xf1, 0x04, 0x5a, 0x2a, 0x27, 0x4d, 0xa5, 0xc1, 0xce, 0xab, 0xa5, 0x05, 0x68,
	0xa6, 0x26, 0xe4, 0x1c, 0x1a, 0xb9, 0x58, 0x6e, 0xa8, 0x6d, 0x1c, 0x57, 0xd0, 0x2c, 0x4a, 0x89,
	0xa5, 0x31, 0x35, 0x2b, 0x51, 0x10, 0xca, 0x53, 0x41, 0x76, 0x2a, 0x4c, 0x3b, 0x3e, 0x73, 0x48,
	0xa6, 0x5c, 0xad, 0xe4, 0xa6, 0x1c, 0xb8, 0xb2, 0xcf, 0x1c, 0x12, 0x9f, 0x40, 0x5b, 0x2a, 0x9d,
	0x15, 0x55, 0x4e, 0xf6, 0xee, 0xba, 0x53, 0x5e, 0xe7, 0x76, 0x48, 0xe9, 0xb6, 0x27, 0x7e, 0x00,
	0xcd, 0xf7, 0x15, 0x96, 0x6b, 0xcf, 0xcf, 0xea, 0xfc, 0x9a, 0x04, 0x55, 0xda, 0xd0, 0x66, 0x85,
	0x44, 0x2f, 0xc0, 0xc6, 0x46, 0xd3, 0x52, 0xcf, 0xbd, 0x00, 0x13, 0x4e, 0x7f, 0x84, 0x00, 0x1f,
	0xb6, 0x1f, 0xe2, 0x6f, 0x01, 0xde, 0x20, 0x6d, 0x9e, 0xe1, 0x9d, 0x3a, 0x83, 0xfd, 0xde, 0x60,
	0x97, 0x9d, 0x71, 0x74, 0xf1, 0xf3, 0xd7, 0xf7, 0x80, 0xf3, 0x7e, 0x72, 0xfe, 0x34, 0xf1, 0xd6,
	0x26, 0x5f, 0x94, 0xfc, 0xca, 0x8f, 0xa1, 0x7b, 0xb9, 0x4f, 0xff, 0xf3, 0xc2, 0x7d, 0xbb, 0x70,
	0x8f, 0xdf, 0xae, 0x2d, 0xd4, 0x07, 0x8c, 0x9f, 0x40, 0xef, 0xc4, 0x7a, 0xb6, 0x21, 0xdc, 0x35,
	0x3d, 0xb8, 0x62, 0x9d, 0x73, 0x23, 0x7e, 0x68, 0x37, 0xde, 0x1b, 0x5c, 0x43, 0x9c, 0xb1, 0x31,
	0x7f, 0x07, 0x3d, 0xf7, 0xf8, 0xff, 0x22, 0x7c, 0xd7, 0x52, 0xaf, 0x7b, 0x7c, 0x5d, 0xf7, 0x47,
	0xe8, 0x1d, 0xd9, 0xbb, 0xff, 0x6f, 0xd0, 0xfb, 0x76, 0x67, 0x3f, 0xee, 0xd6, 0x76, 0xce, 0xd8,
	0x78, 0xc4, 0x0e, 0xd8, 0xa7, 0x96, 0xfd, 0x53, 0x3c, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x2c,
	0x49, 0xeb, 0x2a, 0x67, 0x04, 0x00, 0x00,
}
